version: '3'

services:
    postgres:
        image: postgres
        container_name: postgres_todo_api
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - todo_network

networks:
    todo_network:
        driver: bridge

volumes:
    postgres-data: null
